// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_go_the_distance = "CgkIiuiYy6IOEAIQDg"; // <GPGSID>
        public const string achievement_a_part_of_life = "CgkIiuiYy6IOEAIQCw"; // <GPGSID>
        public const string achievement_make_a_splash = "CgkIiuiYy6IOEAIQCQ"; // <GPGSID>
        public const string achievement_i_believe_i_can_fly = "CgkIiuiYy6IOEAIQAg"; // <GPGSID>
        public const string achievement_a_fresh_start = "CgkIiuiYy6IOEAIQEA"; // <GPGSID>
        public const string achievement_i_can_see_clearly_now = "CgkIiuiYy6IOEAIQAA"; // <GPGSID>
        public const string achievement_were_alike = "CgkIiuiYy6IOEAIQBQ"; // <GPGSID>
        public const string achievement_better_together = "CgkIiuiYy6IOEAIQAw"; // <GPGSID>
        public const string achievement_mountaineer = "CgkIiuiYy6IOEAIQCA"; // <GPGSID>
        public const string achievement_painter = "CgkIiuiYy6IOEAIQEw"; // <GPGSID>
        public const string achievement_hackerman = "CgkIiuiYy6IOEAIQEQ"; // <GPGSID>
        public const string achievement_gladiator = "CgkIiuiYy6IOEAIQFA"; // <GPGSID>
        public const string achievement_rampage = "CgkIiuiYy6IOEAIQDw"; // <GPGSID>
        public const string achievement_taxidermist = "CgkIiuiYy6IOEAIQEg"; // <GPGSID>
        public const string achievement_baby_steps = "CgkIiuiYy6IOEAIQAQ"; // <GPGSID>
        public const string achievement_experienced_creator = "CgkIiuiYy6IOEAIQDQ"; // <GPGSID>
        public const string achievement_heavyweight_champion = "CgkIiuiYy6IOEAIQBg"; // <GPGSID>
        public const string achievement_overpowered = "CgkIiuiYy6IOEAIQCg"; // <GPGSID>
        public const string achievement_on_a_mission = "CgkIiuiYy6IOEAIQDA"; // <GPGSID>
        public const string achievement_minigamer = "CgkIiuiYy6IOEAIQFQ"; // <GPGSID>
        public const string achievement_gray_hairs = "CgkIiuiYy6IOEAIQBw"; // <GPGSID>
        public const string achievement_speed_demon = "CgkIiuiYy6IOEAIQBA"; // <GPGSID>

}

